server:
  port: 1239
  error:
    include-message: always

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

xdisx:
  cors:
    origins:
      - http://localhost:4200