spring:
  application:
    name: customer-app
  profiles:
    active: local

  xdisx:
    environment: LOCAL
    customer:
      openfeign:
        logLevel: BASIC
      contract:
        client-name: contract-app